### ISSUE TITLE
如何添加本地音乐源？

### ISSUE THREAD

**Issue by masterrite** [EYHN/hexo-tag-cplayer#5]
您好！

我想要在hexo中添加电脑本地音乐源的话应该如何输入source部分？

谢谢！

**Comment by mapxn** [comment]
你可以试一下相对路径，当然，绝对路径是一定可以的。


```yml
# 绝对路径
{% cplayer autoplay %}
- name: チルドレンレコード # name
  artist: 96猫,伊東歌詞太郎 # music artist
  poster: https://cplayer.js.org/801422833716a4f0f96ff6dff1f77dfe.jpg # music poster
  src: https://masterrite.github.io/assert/abc.mp3 # 绝对路径
- 27955597 # add music by 163music ID 
{% endcplayer %}
```

```yml
# 相对路径
{% cplayer autoplay %}
- name: チルドレンレコード # name
  artist: 96猫,伊東歌詞太郎 # music artist
  poster: https://cplayer.js.org/801422833716a4f0f96ff6dff1f77dfe.jpg # music poster
  src: /assert/abc.mp3 # 相对路径
- 27955597 # add music by 163music ID 
{% endcplayer %}
```
